kind: Secret
metadata:
  name: my-secret
  namespace: default
stringData:
  source-key: "{\"pushed\":\"saiyam\"}"
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pushsecret-example # Customisable
  namespace: default # Same of the SecretStores
spec:
  refreshInterval: 10s 
  secretStoreRefs: 
    - name: vault-backend
      kind: SecretStore
  selector:
    secret:
      name: my-secret 
  data:
    - match:
        secretKey: source-key
        remoteRef:
          remoteKey: pushed
